# ----------------------- #
#      Jekyll Server      #
# ----------------------- #
# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://wen-bing.github.io
title: Wenbin's Blog
subtitle: A Programmer's Blog
author: Wenbin Ma
simple_search: http://google.com/search
description: 
keywords: node.js, javascript, git, webkit, npapi, V8, browser, html, linux, debian, Android, C, C++, Qt, ruby, NO SQL, mongodb

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%Y-%m-%d"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: Wenbin Ma<mawenb@gmail.com>
# ----------------------- #
# Site path
# ----------------------- #
archives_path: /archives.html
tags_path: /tags.html
about_path: /about.html

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
auto: true
#root: /
permalink: /blog/:year-:month-:day/:title/
plugins: plugins
markdown: kramdown
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 8          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 8       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
titlecase: true       # Converts page and post titles to titlecase
exclude: ["config.rb", ".gitignore", "_sass", "CNAME", "README.md"]
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: wen-bing
github_repo_count: 4
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: wun-bing
twitter_tweet_count: 8 
twitter_show_replies: false
twitter_follow_button: false
twitter_show_follower_count: false
twitter_tweet_button: true

#JiaThis Sharing 
jiathis_share_button: true

#Show Weibo
weibo_msg: false

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: mawenb@gmail.com
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count:

# Disqus Comments
disqus_short_name: wenbingsblog
disqus_show_comment_count: false
disqus_aside_comment_count: 8
disqus_aside_avatar_size: 32
disqus_aside_comment_excerpt_length: 200

# Google Analytics
#google_analytics_tracking_id: UA-30583028-1

# Facebook Like
facebook_like: false
